### ISSUE TITLE
[Support]: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by digimangos** [github/gh-valet#63]
### What operating system are you using?

- [ ] Linux
- [ ] macOS
- [X] Windows

### What version of the tool are you using?

**0.1.0.13168 (27eaf8ab1f68c1c9dcfcf665a52ba6f1a5686504)**

### What happened?

When executing an audit of pipelines from ADO, several pipelines fail with the following error:
Message: undefined method `[]' for nil:NilClass

I believe the customer is executing this in windows, but using WSL prompt.

### Relevant log output

```shell
There was an error extracting the Azure DevOps pipeline.
Message: undefined method `[]' for nil:NilClass
/usr/local/bundle/gems/valet-0.1.0.13168/lib/valet/services/azure_devops/pipeline/extract_pipeline.rb:46:in `extract'
/usr/local/bundle/gems/valet-0.1.0.13168/lib/valet/services/azure_devops/extract_all_pipelines.rb:20:in `block (3 levels) in call'
/usr/local/bundle/gems/valet-0.1.0.13168/lib/valet/models/thread_collection.rb:7:in `block in perform_later'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/ivar.rb:169:in `safe_execute'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/future.rb:55:in `block in execute'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaguereca** [comment]
Hey! Ok so after taking a look at the error it looks like we are not gracefully handling a case where Valet is not finding the pipeline. Could you confirm with the client that the following pipelines exist? 

```
Valet Audit Error Catcher

Returning pipelines containing error: 'undefined method `[]' for nil:NilClass'

Total pipelines with this error: 8
Run on: 2022-07-14 07:43:08 -0700

1. Error message: There was an error extracting the Azure DevOps pipeline.
Message: undefined method `[]' for nil:NilClass
File name: /Users/bguereca/Downloads/Wolters-Kluwer-Basecone-main/valet-pipeline-analysis/results-20220629/Basecone/Basecone.Basecone-TestCafe-E2E.error.txt
URL: https://dev.azure.com/basecone-team/4fb6019a-2ebf-419c-9822-b25ecd3808ef/_build/definition?definitionId=293

2. Error message: There was an error extracting the Azure DevOps pipeline.
Message: undefined method `[]' for nil:NilClass
File name: /Users/bguereca/Downloads/Wolters-Kluwer-Basecone-main/valet-pipeline-analysis/results-20220629/Basecone/Basecone.Basecone-Backend-BusinessIntelligenceService.error.txt
URL: https://dev.azure.com/basecone-team/4fb6019a-2ebf-419c-9822-b25ecd3808ef/_build/definition?definitionId=332

3. Error message: There was an error extracting the Azure DevOps pipeline.
Message: undefined method `[]' for nil:NilClass
File name: /Users/bguereca/Downloads/Wolters-Kluwer-Basecone-main/valet-pipeline-analysis/results-20220629/Basecone/Basecone-CRM.error.txt
URL: https://dev.azure.com/basecone-team/4fb6019a-2ebf-419c-9822-b25ecd3808ef/_build/definition?definitionId=318

4. Error message: There was an error extracting the Azure DevOps pipeline.
Message: undefined method `[]' for nil:NilClass
File name: /Users/bguereca/Downloads/Wolters-Kluwer-Basecone-main/valet-pipeline-analysis/results-20220629/Basecone/Basecone.Basecone-BackOffice-Frontend.error.txt
URL: https://dev.azure.com/basecone-team/4fb6019a-2ebf-419c-9822-b25ecd3808ef/_build/definition?definitionId=374

5. Error message: There was an error extracting the Azure DevOps pipeline.
Message: undefined method `[]' for nil:NilClass
File name: /Users/bguereca/Downloads/Wolters-Kluwer-Basecone-main/valet-pipeline-analysis/results-20220629/Basecone/Basecone.Basecone-Developers-Static.error.txt
URL: https://dev.azure.com/basecone-team/4fb6019a-2ebf-419c-9822-b25ecd3808ef/_build/definition?definitionId=376

6. Error message: There was an error extracting the Azure DevOps pipeline.
Message: undefined method `[]' for nil:NilClass
File name: /Users/bguereca/Downloads/Wolters-Kluwer-Basecone-main/valet-pipeline-analysis/results-20220629/Basecone/Basecone.PushNotifications.error.txt
URL: https://dev.azure.com/basecone-team/4fb6019a-2ebf-419c-9822-b25ecd3808ef/_build/definition?definitionId=335

7. Error message: There was an error extracting the Azure DevOps pipeline.
Message: undefined method `[]' for nil:NilClass
File name: /Users/bguereca/Downloads/Wolters-Kluwer-Basecone-main/valet-pipeline-analysis/results-20220629/Basecone/Basecone-Backend-MailImporter.error.txt
URL: https://dev.azure.com/basecone-team/4fb6019a-2ebf-419c-9822-b25ecd3808ef/_build/definition?definitionId=353

8. Error message: There was an error extracting the Azure DevOps pipeline.
Message: undefined method `[]' for nil:NilClass
File name: /Users/bguereca/Downloads/Wolters-Kluwer-Basecone-main/valet-pipeline-analysis/results-20220629/Basecone/Basecone.Basecone-Docs.error.txt
URL: https://dev.azure.com/basecone-team/4fb6019a-2ebf-419c-9822-b25ecd3808ef/_build/definition?definitionId=366

```

**Comment by digimangos** [comment]
@begonaguereca, I've asked for feedback regarding the first issue.

Yes we created a credential file. I thought most of these errors had disappeared because they were a lot worse before creating the file. Hmmm, I can look in to that with them.

**Comment by begonaguereca** [comment]
@digimangos closing the issue for now since your engagement with this client is over!
