### ISSUE TITLE
[Support]: SSL error when using valet for azure devops to Github Enterprise trial org pipeline migration

### ISSUE THREAD

**Issue by utsav-elux** [github/gh-valet#70]
### What operating system are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### What version of the tool are you using?

root@ubuntuvm:~# gh valet version
gh version 2.13.0 (2022-06-22)
gh valet	github/gh-valet	v0.1.11
valet-cli	v0.1.0.13458

### What happened?

gh valet audit azure-devops -o .

error:
**13:07:28] SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

### Relevant log output

```shell
# Logfile created on 2022-08-22 13:07:25 +0000 by logger.rb/v1.4.2
I, [2022-08-22T13:07:25.443898 #1]  INFO -- : Using GitHub Features: 'all'
I, [2022-08-22T13:07:25.444099 #1]  INFO -- : Auditing 'https://dev.azure.com/ADM-BhattUts/ADM-BhattUts/Personal/_build'
I, [2022-08-22T13:07:25.479696 #1]  INFO -- request: GET https://dev.azure.com/ADM-BhattUts/Personal/_apis/build/definitions?api-version=5.0&includeAllProperties=true&queryOrder=lastModifiedDescending
I, [2022-08-22T13:07:26.253521 #1]  INFO -- : Tracking metrics using event id '4b662c92-4cdb-4e36-8e1e-057fa25d8027'
I, [2022-08-22T13:07:26.263688 #1]  INFO -- request: POST https://valet.azurewebsites.net/api/track/metric
I, [2022-08-22T13:07:28.352923 #1]  INFO -- response: Status 200
E, [2022-08-22T13:07:28.354694 #1] ERROR -- : SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
/usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
/usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
/usr/local/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/local/lib/ruby/2.7.0/net/http.rb:932:in `start'
/usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'
/usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:129:in `request_with_wrapped_block'
/usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
/usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/adapter.rb:50:in `connection'
/usr/local/bundle/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/middleware.rb:18:in `call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/response/logger.rb:25:in `call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/request/authorization.rb:51:in `call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/request/retry.rb:148:in `call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/middleware.rb:18:in `call'
/usr/local/bundle/gems/faraday-http-cache-2.4.1/lib/faraday/http_cache.rb:286:in `fetch'
/usr/local/bundle/gems/faraday-http-cache-2.4.1/lib/faraday/http_cache.rb:190:in `process'
/usr/local/bundle/gems/faraday-http-cache-2.4.1/lib/faraday/http_cache.rb:141:in `call!'
/usr/local/bundle/gems/faraday-http-cache-2.4.1/lib/faraday/http_cache.rb:121:in `call'
/usr/local/bundle/gems/faraday_middleware-1.2.0/lib/faraday_middleware/request/encode_json.rb:26:in `call'
/usr/local/bundle/gems/faraday_middleware-1.2.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/rack_builder.rb:154:in `build_response'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/connection.rb:511:in `run_request'
/usr/local/bundle/gems/faraday-1.7.1/lib/faraday/connection.rb:200:in `get'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/adapters/azure_devops/client.rb:129:in `block in fetch_all'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/adapters/azure_devops/client.rb:128:in `loop'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/adapters/azure_devops/client.rb:128:in `fetch_all'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/adapters/azure_devops/client.rb:39:in `fetch_all_pipelines'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/services/azure_devops/extract_all_pipelines.rb:18:in `block in call'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/services/azure_devops/extract_all_pipelines.rb:17:in `each'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/services/azure_devops/extract_all_pipelines.rb:17:in `call'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/commands/audit.rb:11:in `block in call'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/logger.rb:86:in `with_progress_bar'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/commands/audit.rb:10:in `call'
/usr/local/bundle/gems/valet-0.1.0.13458/lib/valet/subcommands/audit.rb:48:in `azure_devops'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/valet-0.1.0.13458/exe/valet:16:in `<top (required)>'
/usr/local/bundle/bin/valet:23:in `load'
/usr/local/bundle/bin/valet:23:in `<main>'
I, [2022-08-22T13:07:28.359377 #1]  INFO -- request: POST https://valet.azurewebsites.net/api/track/exceptions
I, [2022-08-22T13:07:30.074436 #1]  INFO -- response: Status 200
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utsav-elux** [comment]
Thanks @ethanis, this suggestion works
